export const GET_ALL_SHIPMENT_DETAILS = "GET_SHIPMENT_DETAILS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_SINGLE_SHIPMENT_DETAILS = "GET_SINGLE_SHIPMENT_DETAILS";
export const POST_SHIPMENT_NAME = "POST_SHIPMENT_NAME";
